config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'homes/edit'

  get 'homes/index'

  get 'homes/book_ticket'
  get 'homes/login'
  get 'homes/logout'
  get 'homes/register'
  get 'homes/edit_userinfo'
  get 'homes/editing_userinfo'
  get 'homes/userinfo'
  get 'homes/future_order'
  get 'homes/last_order'
  get 'homes/return_ticket'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/route.rb
class Route < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
# encoding: UTF-8
class HomesController < ApplicationController
  def index
   @m = Route.all
   # @is_order = params[:is_o]
   if  params[:order_info] == nil
     @is_order = -1
     params[:order_info] =nil
   elsif params[:order_info].to_i == 1
     @is_order = 1
     params[:order_info] = nil
   elsif params[:order_info].to_i == 0
     @is_order = 0
     params[:order_info] = nil
   end

   # if params[:user]!=nil
   #    session[:u] = params[:user]
   # end
  end


  def book_ticket
     #@m = Route.all.where start_end :params[:id]
     #@m.ticket_num = @m.ticket_num - 1
     # @is_order = Order.where :route_id => params[:format].to_i, :user=> session[:user]['name']
     @o = Order.find_by_route_id_and_user(params[:format],session[:user]['name'])
     # @is_order = @is_order1.find_by_user(session[:user]['name'])
     if @o != nil
      # if @is_order.user= session[:user]['name']
         @order_state = 1
       else
       @x =Route.find(params[:format])
       if @x.ticket_num <= 0
         @x.ticket_num =0
         @x.save!
       else
         # 票数目减1
         @x.ticket_num = @x.ticket_num - 1
         # @x.ticket_num = 2
         @x.save!

         # 产生订单
         @o = Order.new()
         @o.user = session[:user]['name']
         @o.route_id = @x.id
         @o.ticket_id = 'T-'+Time.new.strftime('%Y%m%d%H%M%S')
         @o.save!
         @order_state = 0
       end
      end
     # puts @x
     redirect_to homes_index_path(:order_info=>@order_state)
  end

  def login
     if (params[:email]!=nil) && (params[:pwd]!=nil)
        @e = params[:email][:email]
        @p = params[:pwd]
        # @u = User.all.where name:@n,password:@p
        @u = User.find_by_email(@e)
        if @u!=nil
          if(@u.password==@p)
            @t='登录成功'
            # session[:user] = params[:name][:name]
            session[:user] = @u
            redirect_to homes_index_path()
          else  @t='账号或密码错误'
          end
        end

     end
  end

  def logout
    session[:user] = nil
    redirect_to homes_index_path()
  end

  def register
      if (params[:name]!=nil) && (params[:pwd]!=nil) && (params[:email]!=nil) && (params[:tel]!=nil)
        @register_name = params[:name][:name]
        @register_pwd = params[:pwd]
        @register_email = params[:email][:email]
        @register_tel = params[:tel][0]
        # @register_role = params[:role]

        if @register_name == ''
          @name_info = '(用户名不能为空！)'
        end

        if @register_pwd == ''
          @pwd_info = '(密码不能为空!)'
        end

        if @register_email == ''
          @email_info = '(邮箱不能为空!)'
        end

        if @register_tel == ''
          @tel_info = '(电话不能为空!)'
        end

        if  (@register_name != '') &&
            (@register_pwd != '') &&
            (@register_email != '') &&
            (@register_tel != '')
            if User.find_by_email(@register_email)!=nil
              @info = '该邮箱已注册，请更换邮箱！'
            elsif
              @u=User.new();
              @u.name = @register_name
              @u.email = @register_email
              @u.password = @register_pwd
              @u.role = 'student'
              @u.telephone_number = @register_tel
              @u.save!
              session[:user] = @u
              redirect_to homes_index_path
            end
        end
      end
  end

  def edit_userinfo

  end

  def editing_userinfo

       # if params[:need_edit]
        @u = User.find(session[:user]['id'])
        @u.name= params[:name]
        @u.password = params[:pwd]
        @u.telephone_number = params[:tel]
        @u.save!
        session[:user] = @u
        redirect_to homes_userinfo_path
       # end
  end

  def edit_userinfo

  end

  def future_order
    if session[:user]!=nil
      @order = Order.all.where user:(session[:user]['name'])
    end
  end

  def last_order
    if session[:user]!=nil
      @order = Order.all.where user:(session[:user]['name'])
    end
  end

  def return_ticket
    @order = Order.find(params[:return_id])
    @order.destroy
    redirect_to homes_future_order_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/edit_userinfo.html.erb


<!-- end header -->
<div class="row-2">
  <div class="container_12">
    <div class="grid_12">
      <div class="flexslider">
	  <div class="grid_12 ident-bot-2">
      <div class="block-2"> <img class="img-border fleft" src="/assets/user_img.jpg" alt="" />
        <div class="block-2-1">

		<div id="confirm">
          <%if session[:user] != nil%>
        <%=form_tag  homes_editing_userinfo_path(:name,:pwd,:tel,:meed_edit=>1), :method => :get do %>
            <fieldset>

            <label >Name<br><%=text_field_tag :name%></label><br>
            <label >Email<br><%=email_field_tag 'email',session[:user]['email'],disabled:true%><br>
            <label >Password<br><%=text_field_tag :pwd%></label><br>
            <label >Telphone<br><%=telephone_field_tag :tel%></label><br>
              <br><br><div ></div>
            <div class="btns"><%=submit_tag "提    交"%></div>
            </fieldset>
         <%end%>
          <%else%>
              <br> <br> <br><label style="font-size: 30px;">您尚未登录，请登录后查看个人信息！</label>
          <%end%>
        </div>


		</div>
        <div class="clear"></div>
		</div>
		</div>
      </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>


app/views/homes/future_order.html.erb

<!-- end header -->
<div class="row-2">
  <div class="container_12">

    <div class="grid_12">

      <div class="flexslider">
        <table class="imagetable">

          <tr>
            <th>车票编号</th>
            <th>发车时间</th>
            <th>路线</th>
            <th>票价</th>
            <th>操作</th>
          </tr>
          <%if session[:user]!=nil %>
          <% @order.each do |od|%>
              <%@route = Route.find(od.route_id)%>
              <%@drive_time = @route.drive_data.strftime('%Y%m%d')+@route.drive_time.to_time.strftime('%H%M')%>
              <%@now_time = Time.new.strftime('%Y%m%d%H%M')%>
              <%if @drive_time < @now_time %>
                  <tr>


                    <th><%=od.ticket_id %></th>

                    <th>

                      <%=@route.drive_data.strftime('%Y年%m月%d日')+' '+@route.drive_time%>
                    </th>
                    <th><%=@route.start_end %></th>
                    <th><%=@route.price %></th>
                    <!--<th><a class="button-red ident-bot-2" href="evaluate.html">退票</a></th>-->
                    <th><%=link_to '退票', homes_return_ticket_path(:return_id => od.id)%></th>

                  </tr>
              <%end%>
          <%end%>

          <%end%>
        </table>

      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>
</div>


app/views/homes/index.html.erb
<!--<!DOCTYPE html>-->
<!--<html >-->
<!--<head>-->
  <title>足下</title>
  <!--<meta charset="utf-8" />-->
  <!--<meta name="viewport" content="width=device-width; initial-scale=1.0" />-->
  <!--<link rel="stylesheet" href="css/style.css" media="screen" />-->
  <!--<link rel="stylesheet" type="/text/css" href="css/graphslide.css"/>-->
  <!--<link rel="icon" href="images/favicon.ico" type="image/x-icon" />-->
  <!--<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />-->
  <!--<script src="/jquery-1.7.2.min.js"></script>-->

  <!--<script src="/jquery_ujs.js"></script>-->

  <!--[if lt IE 9]>
  <!--<script src="/html5.js"></script>-->
  <link rel="stylesheet" href="/ie.css">


  <!--<script type="text/JavaScript">-->
      <!--function error(){-->
          <!--alert('您已经预丁过该车票?');-->
<!--//          history.go(-1);-->
      <!--}-->
  <!--</script>-->

  <!--<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
<!--</head>-->
<!--<body id="page1">-->
<!-- header -->


<!-- end header -->
<div class="row-2">
  <div class="container_12">
    <div class="grid_12">
      <div class="flexslider">
        <div class="box">
          <ul class="list">
            <li><img class="slide" src="/assets/ps1.jpg" height="375" /></li>
            <li><img class="slide" src="/assets/ps2.jpg" height="375" /></li>
            <li><img class="slide" src="/assets/ps3.jpg" height="375" /></li>
            <li><img class="slide" src="/assets/ps4.jpg" height="375" /></li>
          </ul>
          <div class="index">
            <a href="javascript:" class="index_1">1</a>
            <a href="javascript:" class="index_2">2</a>
            <a href="javascript:" class="index_3">3</a>
            <a href="javascript:" class="index_4">4</a>
          </div>
        </div>
        <div class="flex-caption">
          <div class="flex-bg">
            <div class="flex-border">
              <div class="slide-text-1 ident-bot-1">简介</div>
              <div class="slide-text-2">中国科学院大学（英文名 ：University of Chinese Academy of Sciences），简称"国科大"，是国家教育部正式批准成立的一所以研究生教育为主的科教融合、独具特色的高等学校。国科大的前身是中国科学院研究生院，成立于1978年，是经党中央国务院批准创办的新中国第一所研究生院，培养了我国的第一个理学博士、第一个工学博士、第一个女博士、第一个双学位博士。经教育部批准，国科大从2014年起开始招收本科生。<a href="#">Click Here</a></div>

            </div>
          </div>
        </div>

      </div>

      <table>
        <!--<tr>-->
          <!--<th><%=@is_order%></th>-->
        <!--</tr>-->


          <%if @is_order == 1%>
            <tr > <th style="background: red" colspan="5">您已经预定过该车票!</th></tr>
          <%elsif @is_order == 0%>
            <tr >  <th style="background:blue" colspan="5">恭喜您成功预定！</th></tr>
          <%elsif @is_order == -1%>

          <%end%>

        <tr>
          <th>路线</th>
          <th>发车时间</th>
          <th>余票</th>
          <th>票价</th>
          <th>操作</th>
        </tr>

        <% @m.each do |mm| %>


        <tr>
          <!--<th><%=mm.id%></th>-->
          <th><%=mm.start_end %></th>

          <th><%=mm.drive_data.strftime('%Y-%m-%d').to_s%></th>
          <th><%=mm.ticket_num%></th>
          <th><%=mm.price %></th>
          <th><%= link_to_if (session[:user]!=nil && mm.ticket_num>0), '预定', homes_book_ticket_path(mm),:class=>'button-blue'%>
            <!--<%if @order_info!=nil%>-->
            <!--<script>error()</script>-->
                <!--<%end%>-->
          &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to_if  (session[:user]!=nil),"关注", homes_book_ticket_path(mm),:class=>"button-red"%></th>

        </tr>

        <% end %>
      </table>

    </div>
  </div>

  <div style="height: 20px">

  </div>

</div>
</div>



<!-- footer -->

<!--<script src="js/custom.js"></script>-->

<!--</body>-->
<!--</html>-->

app/views/homes/last_order.html.erb
<div class="row-2">
  <div class="container_12">

    <div class="grid_12">
		
      <div class="flexslider">
		<table >
            <tr >
                <th>车票编号</th>
                <th>发车时间</th>
                <th>路线</th>
				<th>票价</th>
				<th>操作</th>
            </tr>
          <%if session[:user]!=nil %>
          <% @order.each do |od|%>
          <%@route = Route.find(od.route_id)%>
          <%@drive_time = @route.drive_data.strftime('%Y%m%d')+@route.drive_time.to_time.strftime('%H%M')%>
          <%@now_time = Time.new.strftime('%Y%m%d%H%M')%>
          <%if @drive_time > @now_time %>
            <tr>


                <th><%=od.ticket_id %></th>

                <th>

                  <%=@route.drive_data.strftime('%Y年%m月%d日')+' '+@route.drive_time%>
                </th>
				<th><%=@route.start_end %></th>
				<th><%=@route.price %></th>
				<th><a class="button-red ident-bot-2" href="evaluate.html">评价</a></th>

            </tr>
          <%end%>
          <%end%>
          <%end%>
        </table>

      </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>



app/views/homes/login.html.erb
<!--<!DOCTYPE html>-->
<!--<head>-->
<!--<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
<title>登录界面</title>

<!--<link rel="stylesheet" type="text/css" href="/body.css"/>-->
<!--<link rel="stylesheet" type="text/css" href="/stylelogin.css" />-->


<!--</head>-->
<!--<body >-->


<body style="background-color: #339bb9">
<div class="container">
	<section id="content">
		<%=form_tag homes_login_path(:emal,:pwd), :method => :get do %>

			<h1>登录</h1>
            <h1 style="color: red"><%=@t%></h1>
            <div style="text-align: left;font-size: 20px">&nbsp;&nbsp;&nbsp;邮&nbsp;箱 </div>
			<div>
             <%= text_field :email,'email',placeholder:'请输入邮箱地址'%>
			</div>
            <div style="text-align: left;font-size: 20px">&nbsp;&nbsp;&nbsp;密&nbsp;码 </div>
			<div>
                <%= password_field_tag :pwd,''%>
			</div>

            <div class="">
				<span class="help-block u-errormessage" id="js-server-helpinfo">&nbsp;</span>			</div>
			<div>
				<!-- <input type="submit" value="Log in" /> -->

                <%=submit_tag "登录" %>
				<!--<a href="#">忘记密码?</a>-->
				<!--<a href="register.html">马上注册</a>-->
			</div>
		<!-- form -->
          <% end%>
	</section><!-- content -->
</div>
<!-- container -->

<div style="height: 100px"></div>
<!--</body>-->
<!--</html>-->

app/views/homes/register.html.erb
<%# encodng: utf-8%>
<!DOCTYPE html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>注册界面</title>

  <link rel="stylesheet" type="text/css" href="/body.css"/>
  <link rel="stylesheet" type="text/css" href="/stylelogin.css" />
</head>
<body >



<div class="container">
  <section id="content">
    <%=form_tag homes_register_path(:name,:pwd,:email,:tel,:role), :method => :get do %>

        <h1>登录</h1>
        <h1 style="color: red"><%=@info%></h1>
        <div style="text-align: left;font-size: 20px">&nbsp;&nbsp;&nbsp;用户名<font color="red"><%=@name_info%></font> </div>
        <div>
          <%= text_field :name,'name',placeholder:'请输入用户名称'%>
        </div>
        <div style="text-align: left;font-size: 20px">&nbsp;&nbsp;&nbsp;邮&nbsp;箱<font color="red"><%=@email_info%></font> </div>
        <div>
          <%= text_field :email,'email',placeholder:'请输入邮箱地址'%>
        </div>
        <div style="text-align: left;font-size: 20px">&nbsp;&nbsp;&nbsp;密&nbsp;码 <font color="red"><%=@pwd_info%></font></div>
        <div>
          <%= password_field_tag :pwd,''%>
        </div>
        <div style="text-align: left;font-size: 20px">&nbsp;&nbsp;&nbsp;电&nbsp;话 <font color="red"><%=@tel_info%></font></div>
        <div>
          <%= text_field :tel,''%>
        </div>
        <!--<div>-->
          <!--<label>角色:</label>-->
          <!--<label>学生:</label>-->
          <!--<%=radio_button_tag :role, 'student',true%>-->
          <!--&nbsp;&nbsp;-->
          <!--<label>助教:</label>-->
          <!--<%=radio_button_tag :role, 'assistant'%>-->
        <!--</div>-->

        <div >
          <!-- <input type="submit" value="Log in" /> -->

          <%=submit_tag "提    交"%>

        </div>
        <!-- form -->
    <% end%>
  </section><!-- content -->
</div>
<!-- container -->

</body>
</html>

app/views/homes/userinfo.html.erb


<!-- end header -->
<div class="row-2">
  <div class="container_12">
    <div class="grid_12">
      <div class="flexslider">
	  <div class="grid_12 ident-bot-2">
      <div class="block-2"> <img class="img-border fleft" src="/assets/user_img.jpg" alt="" />
        <div class="block-2-1">

		<div id="confirm">
          <%if session[:user] != nil%>
        <form>
            <fieldset>
            <label >Name<br><%=text_field_tag 'name', session[:user]['name'],disabled:true%></label><br>
            <label >Email<br><%=email_field_tag 'email',session[:user]['email'],disabled:true%><br>
            <label >Password<br><%=text_field_tag 'pwd', session[:user]['password'],disabled:true%></label><br>
            <label >Telphone<br><%=telephone_field_tag 'tel', session[:user]['telephone_number'],disabled:true%></label><br>
              <br><br><div ></div>
            <div class="btns"><%=link_to '修改个人信息', homes_edit_userinfo_path(:edit=>0),class:'button-red'%></div>
            </fieldset>
          </form>
          <%else%>
              <br> <br> <br><label style="font-size: 30px;">您尚未登录，请登录后查看个人信息！</label>
          <%end%>
        </div>


		</div>
        <div class="clear"></div>
		</div>
		</div>
      </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>


app/views/layouts/application.html.erb
<%# encoding: utf-8%>
<!DOCTYPE html>
<html>
<head>
  <!--<title>足下</title>-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--<script src="/jquery_ujs.js"></script>-->
  <meta name="viewport" content="width=device-width; initial-scale=1.0" />


</head>
<body>

<header>
  <div class="row-1">
    <div class="container_12">
      <div class="grid_12">
        <div class="logo fleft">
          <h1><a href="index.html">12306plus</a></h1>
          <div class="slogan">足下</div>
        </div>
        <div class="login">
          <ul>
            <% if session[:user]==nil%>
                <li><%=link_to "登录", homes_login_path %>&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "注册", homes_register_path %></li>
            <% else%>
                <li><a><%=session[:user]['name']+",  您好！"%>&nbsp;&nbsp;<%=link_to "退出", homes_logout_path %></a></li>

            <%end%>
          </ul>
        </div>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
  <div class="row-3">
    <div class="container_12">
      <div class="grid_12">
        <!-- menu -->
        <nav id="main-nav-menu">
          <ul class="sf-menu">
            <li ><%=link_to '主页',homes_index_path%></li>
            <li><%=link_to '个人信息',homes_userinfo_path%>
            </li>
            <li><a href="#">订票记录</a>
              <ul>
                <li><%=link_to '未出票车票',homes_future_order_path %></li>
                <li><%=link_to '已发车车票',homes_last_order_path %></li>
              </ul>
            </li>
            <li><a href="blog.html">校车风采</a>
              <ul>
                <li><a href="blog.html">Blog</a></li>
                <li><a href="blog-single.html">Blog Details</a></li>
              </ul>
            </li>
            <li><a href="contact.html">联系我们</a></li>

            <li  style="background:#252525;;padding-left: 316px"><a><%="今天是 "+Time.new.strftime('%Y年%m月%d日')%></a></li>
          </ul>


        </nav>


        <!-- end menu -->
        <select id="responsive-main-nav-menu" onChange="javascript:window.location.replace(this.value);">
        </select>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</header>

<%= yield %>

<footer>
  <div class="footer-2">
    <div class="container_12">
      <div class="wrapper">
        <div class="grid_12">
          <div class="policy">&copy; Copyright &copy;中国科学院大学  <a href="http://www.ucas.ac.cn/" target="_blank"></a></div>
          <div class="policy"><%=link_to '管理员登陆','/admin'%></div>

        </div>
      </div>
    </div>
  </div>
</footer>

</body>
</html>